[project]
name = "response-monitor"
version = "0.1.0"
description = "Monitor Response Time of Requests."
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "python-decouple>=3.8",
    "redis>=6.2.0",
    "requests>=2.32.4",
]
